# Project configuration
project_id = "bplsogdsyabqfftwclka"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[realtime]
enabled = true
port = 54327

[functions]
[functions.get-manifest]
verify_jwt = false

[functions.generate-storefront]
verify_jwt = false